export interface ServiceDetail {
  seoTitle: string;
  metaDescription: string;
  title: string;
  lead: string;
  tags: readonly string[];
  scopeEyebrow: string;
  scopeHeading: string;
  scopeIntro: string;
  scope: readonly (readonly [string, string])[];
  systemsHeading: string;
  systemsIntro: string;
  systems: readonly string[];
  fitEyebrow: string;
  fitHeading: string;
  fits: readonly string[];
  boundaryLabel: string;
  boundaryHeading: string;
  boundaryText: string;
  managedEyebrow: string;
  managedHeading: string;
  managedIntro?: string;
  managedSteps: readonly string[];
  faqHeading: string;
  faqIntro: string;
  faqs: readonly (readonly [string, string])[];
  closingHeading: string;
  feedbackHeading: string;
  feedbackPlaceholder: string;
}

/* The four managed-support steps share their titles across every service; only the text differs. */
export const managedStepTitles = ['Define the role', 'Match the experience', 'Onboard the support', 'Manage the relationship'] as const;

/* Task-based shortcuts from the content proposal's services index, for visitors who know the work
   they need covered but not which service it belongs to. */
export const serviceRouter: readonly (readonly [string, string])[] = [
  ['Loan files and settlements', '/services/mortgage-loans'],
  ['Advice administration', '/services/financial-planning'],
  ['Financial records and reconciliation', '/services/accounting-bookkeeping'],
  ['Property and CRM administration', '/services/real-estate-conveyancing'],
  ['Daily business administration', '/services/back-office-admin'],
  ['Campaign and content execution', '/services/digital-marketing'],
];

/* Service page content, taken from SERVICE PAGES_VOA.pdf (docs/updated_src). Deliberate edits: "VOA"
   is written out as "Virtual Office Angels", and two US spellings are Australian. The boundary card
   text predates the PDF (captured from the VOA Content proposal); Insurance uses its own FAQ answer. */
export const serviceDetails: Record<string, ServiceDetail> = {
  "/services/mortgage-loans": {
    seoTitle: "Mortgage Processing Virtual Assistant Support | VOA",
    metaDescription: "Find an experienced mortgage processing virtual assistant for CRM updates, document coordination, lodgement, and settlement support for Australian businesses.",
    title: "Mortgage & Loans Processing Virtual Support",
    lead: "Virtual Office Angels matches mortgage businesses with experienced virtual assistants who support loan administration from application through to settlement, working within your systems and approved procedures.",
    tags: ["Application Administration", "Broker CRM Updates", "Settlement Support"],
    scopeEyebrow: "Virtual loans assistant role scope",
    scopeHeading: "Build reliable virtual loan-processing support around your business needs.",
    scopeIntro: "Start with the work your team needs covered, the systems already in use and the level of responsibility required. We then define a role that fits your process and works alongside your existing team.",
    scope: [
      ["CRM and file setup", "Maintain client records, application stages, notes, and document status in your nominated broker CRM."],
      ["Document coordination", "Prepare checklists, follow up on outstanding documents, and keep files organised for broker review."],
      ["Serviceability preparation", "Enter supplied client information into approved calculators and prepare results for broker review."],
      ["Forms and valuations", "Coordinate valuation orders and prepare discharge, FHOG and other required forms in line with your process."],
      ["Lender research support", "Compile lender product and policy information against criteria set by the broker, ready for broker assessment."],
      ["Lodgement to settlement", "Support file lodgement, track application progress, coordinate updates, and follow up through to settlement."],
    ],
    systemsHeading: "Match the role to the tools you use.",
    systemsIntro: "Our virtual mortgage and loan processing support starts with the outcomes, recurring work, and systems that need coverage. We then define the role around tasks you can document, review, and integrate into your existing team.",
    systems: ["Connective", "Mercury", "Podium", "Salestrekker", "Symmetry", "Flex", "AdviserLogic", "COIN"],
    fitEyebrow: "When to hire a virtual loans assistant",
    fitHeading: "Choose specialised support when loan processing needs more than general admin.",
    fits: [
      "Application administration is taking time away from client conversations and new business.",
      "Files need more consistent document follow-up, CRM updates, and status tracking.",
      "You need someone familiar with mortgage terminology, lender systems, and broker workflows.",
      "You want recruitment, onboarding, and ongoing team support managed through one provider.",
    ],
    boundaryLabel: "Clear role boundaries",
    boundaryHeading: "Support works best with defined authority and review.",
    boundaryText: "The virtual assistant supports administration under your documented procedures. Credit decisions, product recommendations, responsible-lending judgements and regulated advice remain with the broker or appropriately authorised professional.",
    managedEyebrow: "Managed virtual support for Australian mortgage businesses",
    managedHeading: "The role is managed beyond the initial match.",
    managedIntro: "Virtual Office Angels manages the staffing relationship so your business can stay focused on loan-processing quality, client service, and growth. The role is supported around the systems, procedures, and working standards your business requires.",
    managedSteps: [
      "Set the tasks, systems, working hours, permissions, and outcomes expected from the role.",
      "Assess candidates against the mortgage experience, systems knowledge, and working style you need.",
      "Introduce your virtual assistant to your systems, team, and documented procedures.",
      "Receive ongoing HR, payroll, and team support after placement.",
    ],
    faqHeading: "Mortgage & Loan Processing Virtual Assistant FAQs",
    faqIntro: "Quick answers on role scope, systems, and responsibilities.",
    faqs: [
      ["What can a mortgage processing virtual assistant do?", "A mortgage processing virtual assistant can support the administrative work behind a loan file, including CRM updates, document coordination, serviceability preparation, valuations and forms, file lodgement, status tracking and settlement follow-up. We agree on the exact responsibilities during the role-planning stage of our HR-managed Virtual Support Solutions."],
      ["Can the virtual assistant work in our broker CRM?", "Yes, where the role is matched to the relevant system experience. We confirm your CRM, loan-processing platforms, and other system requirements before assessing candidates for the role."],
      ["Does the virtual assistant provide credit advice?", "No. The virtual assistant provides administrative support within your documented procedures and agreed authority. Credit advice, product recommendations, and decisions requiring professional judgement remain with the broker or appropriately authorised professional."],
    ],
    closingHeading: "Tell us what needs coverage, which tools you use, and where mortgage industry experience matters most.",
    feedbackHeading: "What Our Mortgage and Loans Virtual Support Clients Say",
    feedbackPlaceholder: "Feedback currently being gathered.",
  },
  "/services/financial-planning": {
    seoTitle: "Financial Planning Virtual Assistant Support | VOA",
    metaDescription: "Find a financial planning virtual assistant for client admin, review preparation, software updates, and implementation support for Australian businesses.",
    title: "Financial Planning & Admin Support",
    lead: "Virtual Office Angels matches financial planning businesses with experienced virtual assistants who support client administration, review preparation, and implementation tasks within your systems and documented processes.",
    tags: ["Client Administration", "Review Preparation", "Implementation Support"],
    scopeEyebrow: "Virtual financial support role scope",
    scopeHeading: "Keep advice workflows moving with specialised admin support.",
    scopeIntro: "Build the role around the administrative work your financial advisers and support team need covered. We match the required tasks, systems, and level of responsibility to a virtual assistant with relevant financial planning experience.",
    scope: [
      ["Client record management", "Maintain client information, records, and document status across your financial planning software and CRM."],
      ["Meeting preparation", "Prepare meeting packs, client forms and supporting documents ahead of adviser appointments and reviews."],
      ["Review administration", "Track review dates, prepare reminder correspondence and organise information required for upcoming client reviews."],
      ["Advice preparation support", "Assist with data entry, research and document preparation under the direction of your financial adviser."],
      ["Provider coordination", "Follow up on documentation and information with fund managers, insurers, administrators and other providers."],
      ["Implementation support", "Prepare forms, coordinate supporting documents and assist with agreed implementation administration after adviser approval."],
    ],
    systemsHeading: "Match the role to the systems behind the work.",
    systemsIntro: "Tell us which platforms form part of your workflow. We factor relevant system experience into the candidate matching process.",
    systems: ["XPlan", "WealthSolver", "Risk Researcher", "CALM / XTools", "Midwinter", "AdviserLogic"],
    fitEyebrow: "When to hire virtual financial support",
    fitHeading: "Choose specialised support when admin starts taking advisers away from clients.",
    fits: [
      "Client records, meeting packs and review preparation are taking adviser time away from client-facing and revenue-producing work.",
      "Your team needs more consistent follow-up across client files, providers and outstanding documentation.",
      "The role requires familiarity with financial planning terminology, systems, tools, and established advice workflows.",
      "You want recruitment, onboarding, and ongoing team support managed through one provider.",
    ],
    boundaryLabel: "Clear role boundaries",
    boundaryHeading: "Support works best with defined authority and review.",
    boundaryText: "The virtual assistant provides administrative support to the practice. They do not provide personal financial advice, select strategies, make recommendations or replace the review and authorisation required from a licensed adviser.",
    managedEyebrow: "Managed virtual support for Australian financial planning businesses",
    managedHeading: "Your virtual financial support assistant is managed beyond recruitment.",
    managedIntro: "Virtual Office Angels manages the staffing relationship so your team can stay focused on clients, delivering financial advice, and growing the business. Our virtual financial support solution is built around your systems, procedures, and working standards.",
    managedSteps: [
      "Set the tasks, systems, working hours, permissions, and responsibilities required.",
      "Assess candidates against their financial planning industry experience, system knowledge, and role requirements.",
      "Introduce your virtual assistant to your systems, team, and documented processes.",
      "Receive ongoing HR, payroll, and team support after placement.",
    ],
    faqHeading: "Financial Planning & Admin Virtual Assistant FAQs",
    faqIntro: "Quick answers on role scope, systems, and responsibilities.",
    faqs: [
      ["What can a financial planning virtual assistant do?", "A financial planning virtual assistant can support client administration, meeting and review preparation, CRM and software updates, provider follow-ups, document preparation, and agreed implementation tasks. The exact responsibilities are defined around your firm's processes and the level of support required."],
      ["Can the virtual assistant work in our financial planning software?", "Yes, where the role is matched to the relevant system experience. We identify the platforms used by your business, such as XPlan and other financial planning or CRM systems, when defining the role and assessing suitable candidates."],
      ["Can the virtual assistant provide financial advice?", "No. The virtual assistant supports administrative and preparation tasks within your firm's documented procedures. Financial advice, strategy decisions, recommendations, and other activities requiring professional authorisation remain with the appropriate adviser."],
    ],
    closingHeading: "Tell us what needs coverage, which tools you use, and where financial planning industry experience matters most.",
    feedbackHeading: "What Our Financial Planning Virtual Support Clients Say",
    feedbackPlaceholder: "Feedback currently being gathered.",
  },
  "/services/accounting-bookkeeping": {
    seoTitle: "Accounting & Bookkeeping Virtual Assistant Support | VOA",
    metaDescription: "Find an accounting and bookkeeping virtual assistant for invoicing, accounts, payroll administration, reconciliations, and ongoing bookkeeping support.",
    title: "Accounting and Bookkeeping Virtual Support",
    lead: "Virtual Office Angels matches businesses and accounting practices with experienced virtual assistants who support day-to-day bookkeeping, transaction processing, and financial administration within your existing systems and procedures.",
    tags: ["Bookkeeping Support", "Accounts Administration", "Reconciliations"],
    scopeEyebrow: "Accounting & bookkeeping virtual assistant role scope",
    scopeHeading: "Keep routine financial administration accurate and up to date.",
    scopeIntro: "Build the role around the bookkeeping and accounts work your business needs covered regularly. We match tasks, software, and responsibility levels to a virtual assistant with relevant accounting and bookkeeping experience.",
    scope: [
      ["Invoicing support", "Prepare and issue invoices, update records, and track outstanding amounts according to your billing process."],
      ["Accounts payable", "Record supplier invoices, maintain payable records, and prepare payment information for authorised review."],
      ["Accounts receivable", "Maintain debtor records, track outstanding accounts and support agreed payment follow-up processes."],
      ["Payroll administration", "Prepare payroll information, maintain employee records and process routine payroll tasks within your approved system."],
      ["Bank reconciliation", "Reconcile bank and credit card transactions against your accounting records and flag discrepancies for review."],
      ["Reporting preparation", "Maintain ledgers and organise financial records and reports ready for management or accountant review."],
    ],
    systemsHeading: "Match the role to your accounting software and tools.",
    systemsIntro: "Tell us which systems form part of your accounting and bookkeeping process. Relevant software experience is factored into the candidate matching process.",
    systems: ["Xero", "MYOB", "QuickBooks", "Saasu", "Microsoft Excel", "Client Document Systems"],
    fitEyebrow: "When to hire a virtual assistant for accounting & bookkeeping",
    fitHeading: "Choose specialised support when your bookkeeping needs more consistent attention.",
    fits: [
      "Invoicing, reconciliations, or account records are regularly competing with higher-value work.",
      "Accounts payable and receivable need more consistent processing and follow-up.",
      "Financial records need to stay current so management and accountants have reliable information to work from.",
      "You need someone already familiar with accounting software and routine bookkeeping processes.",
    ],
    boundaryLabel: "Clear role boundaries",
    boundaryHeading: "Support works best with defined authority and review.",
    boundaryText: "The virtual assistant works within your approvals and internal controls. Tax advice, audit opinions, statutory sign-off and decisions reserved for a registered accountant, tax agent or business owner remain with those authorised parties.",
    managedEyebrow: "Managed virtual support for Australian businesses",
    managedHeading: "We manage your accounting & bookkeeping VA beyond recruitment.",
    managedIntro: "Virtual Office Angels manages the staffing relationship around the role, so your business has ongoing support for the people, systems, and processes behind day-to-day accounting administration.",
    managedSteps: [
      "Set the accounting/bookkeeping tasks, software, working hours, approval levels, and responsibilities required.",
      "Assess candidates against your accounting software, bookkeeping experience, and role requirements.",
      "Introduce your virtual assistant to your accounts process, systems, reporting requirements, and team.",
      "Receive ongoing HR, payroll, and team support after placement.",
    ],
    faqHeading: "Accounting & Bookkeeping Virtual Assistant FAQs",
    faqIntro: "Quick answers about bookkeeping tasks, software, and how the role works within your existing processes.",
    faqs: [
      ["What can an accounting and bookkeeping virtual assistant do?", "An accounting and bookkeeping virtual assistant can support invoicing, accounts payable and receivable, payroll administration, bank and credit card reconciliation, ledger maintenance, and routine bookkeeping records. The exact responsibilities depend on your business processes and approval requirements."],
      ["What accounting software can the virtual assistant work with?", "Software experience is considered when matching the role. The accounting support team must have experience with common industry platforms including Xero, MYOB, QuickBooks, Saasu, and Excel, with the required systems confirmed before candidate selection."],
      ["Who reviews and approves the work of my virtual assistant?", "Your business determines the approval process and authority attached to the role. The virtual assistant works within those agreed procedures, while financial decisions, tax advice, and matters requiring professional accounting judgement remain with the appropriate person."],
    ],
    closingHeading: "Tell us what needs coverage, which tools you use, and where accounting & bookkeeping experience matters most.",
    feedbackHeading: "What Our Accounting & Bookkeeping Virtual Support Clients Say",
    feedbackPlaceholder: "Feedback is currently being gathered.",
  },
  "/services/insurance-processing": {
    seoTitle: "Insurance Processing Virtual Assistant Support | VOA",
    metaDescription: "Find an insurance processing virtual assistant for policy administration, renewals, claims, CRM updates, and broker support for Australian insurance businesses.",
    title: "Insurance Processing Virtual Support",
    lead: "Virtual Office Angels matches insurance businesses with experienced virtual assistants who support policy administration, renewals, claims processing, and client records within your systems and documented procedures.",
    tags: ["Policy Administration", "Renewals Support", "Claims Processing"],
    scopeEyebrow: "Insurance processing virtual assistant role scope",
    scopeHeading: "Keep insurance processing moving from new business to renewal.",
    scopeIntro: "Build the role around the policy administration and processing work your team needs covered. We match the required tasks, systems, and level of responsibility with a virtual assistant who has relevant insurance industry experience.",
    scope: [
      ["New business processing", "Enter new business details into your CRM, organise supporting documents and maintain application records for broker review."],
      ["Renewals and endorsements", "Process renewal, cancellation and endorsement administration and keep policy information current across your systems."],
      ["Quotation support", "Prepare quotation information and gather the client and risk details required for broker assessment."],
      ["Policy documentation", "Prepare and issue approved renewal notices, policy schedules and supporting documentation in line with your process."],
      ["Claims administration", "Record incoming claims, organise supporting information and track agreed processing steps through your claims workflow."],
      ["Client and broker liaison", "Follow up on documents, provide approved updates and escalate issues requiring broker review or action."],
    ],
    systemsHeading: "Match the role to your insurance systems.",
    systemsIntro: "Tell us which CRM, insurer portals, and processing systems your team works with. Relevant system experience can then support the candidate-matching process.",
    systems: ["Insurance CRM", "Insurer Portals", "Client Records", "Document Management", "Claims Systems"],
    fitEyebrow: "When to hire a virtual assistant for insurance processing",
    fitHeading: "Choose specialised support when insurance processing starts taking broker time.",
    fits: [
      "New business, renewals and endorsements are creating a growing administrative workload.",
      "Client and policy records need more consistent updates and document follow-up.",
      "Claims and renewal activity needs regular tracking so outstanding actions are easier to identify.",
      "The role requires familiarity with insurance terminology, broker workflows, and policy administration.",
    ],
    boundaryLabel: "Clear role boundaries",
    boundaryHeading: "Support works best with defined authority and review.",
    boundaryText: "No. The role supports insurance administration and processing within agreed procedures. Policy recommendations, coverage decisions and other matters requiring professional advice or authorised judgement remain with the appropriate broker or authorised person.",
    managedEyebrow: "Managed virtual support for Australian businesses",
    managedHeading: "We manage your insurance processing virtual assistant beyond recruitment.",
    managedIntro: "Virtual Office Angels manages the staffing relationship so your team can focus on clients, policy advice and business development while routine insurance processing stays organised.",
    managedSteps: [
      "Set the policy-processing tasks, systems, working hours, permissions and responsibilities required.",
      "Assess candidates against your insurance workflow, systems knowledge, and administrative requirements.",
      "Introduce your virtual assistant to your systems, policy processes, documentation standards, and team.",
      "Receive ongoing HR, payroll, and team support after placement.",
    ],
    faqHeading: "Insurance Processing Virtual Assistant FAQs",
    faqIntro: "Quick answers about insurance processing tasks, software, and how the role works within your existing systems and tools.",
    faqs: [
      ["What can an insurance processing virtual assistant do?", "An insurance processing virtual assistant can support new business administration, renewals, endorsements, CRM updates, policy documentation, quotation preparation, claims processing, and client follow-up. Exact responsibilities depend on your systems, procedures, and approval requirements."],
      ["Can a virtual assistant support insurance renewals and claims?", "Yes. A virtual assistant can help with renewal administration, policy documentation, client follow-ups, and recording and processing incoming claims within your established workflow. Matters requiring advice, assessment, or broker judgement are escalated to the appropriate person."],
      ["Can the virtual assistant provide insurance advice?", "No. The role supports insurance administration and processing within agreed procedures. Policy recommendations, coverage decisions and other matters requiring professional advice or authorised judgement remain with the appropriate broker or authorised person."],
    ],
    closingHeading: "Tell us what needs coverage, which tools you use, and where Australian insurance processing experience matters most.",
    feedbackHeading: "What Our Insurance Processing Virtual Support Clients Say",
    feedbackPlaceholder: "Feedback is currently being gathered.",
  },
  "/services/real-estate-conveyancing": {
    seoTitle: "Real Estate Virtual Assistant & Admin Support | VOA",
    metaDescription: "Find a real estate virtual assistant for CRM administration, property listings, prospect follow-up, appointment coordination, and ongoing agency support.",
    title: "Real Estate & Admin Virtual Support",
    lead: "Virtual Office Angels matches real estate businesses with experienced virtual assistants who support property administration, CRM management, prospect follow-up, and day-to-day agency workflows.",
    tags: ["CRM Administration", "Property Listings", "Prospect Follow-Up"],
    scopeEyebrow: "Real estate & admin virtual assistant role scope",
    scopeHeading: "Keep property admin moving while your team stays focused on clients and listings.",
    scopeIntro: "Build the role around the recurring administration behind your agency. We match the tasks, systems, and working requirements to a virtual assistant with relevant real estate support experience.",
    scope: [
      ["CRM administration", "Update contact details, prospect stages, property records, notes, and follow-up activity in your agency CRM."],
      ["Lead administration", "Record new enquiries, organise prospect information, and keep lead lists current for agent follow-up."],
      ["Prospect follow-up", "Complete agreed follow-ups using your agency scripts and processes, then record outcomes for the team."],
      ["Inbox and calendar support", "Organise enquiries, coordinate appointments and keep agent calendars and follow-up schedules up to date."],
      ["Listing administration", "Prepare draft listing information, organise property details and coordinate documents required for agency approval."],
      ["Property file coordination", "Maintain property records, supporting documents and milestone updates across your agency workflow."],
    ],
    systemsHeading: "Match the role to your real estate and admin systems.",
    systemsIntro: "Tell us which CRM, email, calendar, and document platforms sit behind your real estate workflow. Relevant system experience is considered when matching candidates to the role.",
    systems: ["Your Property CRM", "Email & Calendar", "Cloud Documents", "Agency Workflow Tools"],
    fitEyebrow: "When to hire a virtual assistant for real estate processing",
    fitHeading: "Choose specialised support when property admin starts taking agents away from clients.",
    fits: [
      "CRM updates and enquiry records are building up between appointments and inspections.",
      "Prospects need regular follow-up so opportunities do not disappear into an inbox or spreadsheet.",
      "Listing and property files need clearer document, status and milestone tracking.",
      "Agents need calendars, appointments and recurring administration kept organised behind the scenes.",
    ],
    boundaryLabel: "Clear role boundaries",
    boundaryHeading: "Support works best with defined authority and review.",
    boundaryText: "The virtual assistant follows the agency’s approved scripts, authorities and escalation process. Licensed activity, negotiation, legal interpretation and decisions requiring a local or authorised professional stay with the appropriate team member.",
    managedEyebrow: "Managed virtual support for Australian real estate businesses",
    managedHeading: "We manage your real estate virtual assistant beyond recruitment.",
    managedIntro: "Virtual Office Angels manages the staffing relationship so your agents can stay focused on clients, listings and business development while recurring property administration stays organised.",
    managedSteps: [
      "Set the property tasks, systems, working hours, permissions and responsibilities required.",
      "Assess candidates against your real estate workflow, CRM experience, and administrative requirements.",
      "Introduce your virtual assistant to your systems, agency processes, scripts and documentation standards.",
      "Receive ongoing HR, payroll, and team support after placement.",
    ],
    faqHeading: "Real Estate Administrative Virtual Assistant FAQs",
    faqIntro: "Quick answers about property administration, CRM support, and how a real estate virtual assistant can work alongside your local team.",
    faqs: [
      ["What tasks can a real estate virtual assistant handle?", "A real estate virtual assistant can support CRM administration, enquiry management, prospect follow-up, inbox and calendar organisation, listing administration, and property file coordination. The exact responsibilities depend on your agency's systems, processes, and authority levels."],
      ["Can the role be matched to our property CRM?", "Yes. Your CRM and other agency systems are identified during role planning so relevant software experience can be considered when candidates are matched to your requirements."],
      ["Can a virtual assistant help with prospect follow-up?", "Yes. A virtual assistant can complete agreed prospect follow-ups using your agency's approved scripts and processes, record responses, and keep your CRM current for the local team. The existing Virtual Office Angels real estate service also includes cold calling and follow-up support."],
    ],
    closingHeading: "Tell us what needs coverage, which tools you use, and where Australian real estate processing experience matters most.",
    feedbackHeading: "What Our Real Estate Virtual Support Clients Say",
    feedbackPlaceholder: "Feedback is currently being gathered.",
  },
  "/services/back-office-admin": {
    seoTitle: "Executive & Administrative Virtual Assistant Support | VOA",
    metaDescription: "Find an experienced executive and administrative virtual assistant for inboxes, calendars, customer enquiries, documents, and daily business support.",
    title: "Executive & Administrative Virtual Support",
    lead: "Virtual Office Angels matches business owners and leadership teams with experienced virtual assistants who manage recurring administration, executive coordination, and day-to-day business support.",
    tags: ["Executive Assistance", "Inbox & Calendar", "Business Administration"],
    scopeEyebrow: "Executive & administrative virtual assistant role scope",
    scopeHeading: "Keep executive schedules, inboxes, and follow-ups under control.",
    scopeIntro: "Build the role around the recurring work that takes time away from leadership, clients, and business priorities. We match the responsibilities, systems, and working requirements to a virtual assistant with relevant executive and administrative experience.",
    scope: [
      ["Executive assistance", "Coordinate recurring administrative tasks, meeting preparation, follow-ups, and other agreed support for business owners and senior team members."],
      ["Inbox management", "Organise incoming email, prioritise messages, manage agreed responses, and flag matters that need your attention."],
      ["Calendar coordination", "Schedule meetings and appointments, manage calendar changes and coordinate availability with clients and team members."],
      ["Customer support", "Manage routine enquiries, follow agreed response processes and keep client communications moving to the right person."],
      ["Research and data support", "Gather business information, maintain records and organise research or data required for upcoming work and decisions."],
      ["Document administration", "Prepare, format, organise and maintain routine business documents, files and shared records."],
    ],
    systemsHeading: "Match the role to your executive and administrative systems.",
    systemsIntro: "Tell us which communication, scheduling, document and task-management tools sit behind your daily operations. Relevant system experience is considered when we match candidates to the role.",
    systems: ["Microsoft 365", "Google Workspace", "CRM Systems", "Cloud Documents", "Task Management"],
    fitEyebrow: "When to hire an executive & administrative virtual assistant",
    fitHeading: "Choose specialised support when routine admin becomes unmanageable.",
    fits: [
      "Your inbox, diary and recurring follow-ups are taking time away from leadership and client work.",
      "Meetings and appointments need consistent coordination across clients and team members.",
      "Customer enquiries and routine communications need reliable day-to-day attention.",
      "Documents, records and recurring administrative tasks need clearer ownership.",
    ],
    boundaryLabel: "Clear role boundaries",
    boundaryHeading: "Support works best with defined authority and review.",
    boundaryText: "The role follows your documented permissions, approval levels and escalation points. Commercial commitments, legal decisions, sensitive approvals and work outside the agreed authority remain with your nominated team members.",
    managedEyebrow: "Managed virtual support for Australian businesses",
    managedHeading: "We manage your executive and administrative virtual assistant beyond recruitment.",
    managedSteps: [
      "Set the responsibilities, systems, working hours, access levels, and priorities required.",
      "Assess candidates against the executive, administrative, and system experience your business needs.",
      "Introduce your virtual assistant to your team, communication preferences, systems, and working procedures.",
      "Receive ongoing HR, payroll, and team support after placement.",
    ],
    faqHeading: "Executive & Administrative Virtual Assistant FAQs",
    faqIntro: "Quick answers about executive assistance, administrative responsibilities, and how the role fits into your existing business.",
    faqs: [
      ["What can an executive and administrative virtual assistant do?", "An executive and administrative virtual assistant can support inbox and calendar management, appointments, meeting coordination, customer enquiries, document administration, research, and recurring administrative tasks. Exact responsibilities depend on how your business operates."],
      ["Can the virtual assistant support a business owner or executive directly?", "Yes. The role can be structured around the recurring administration and coordination a business owner, executive, or leadership team needs. Responsibilities, access, and approval levels are agreed before the role begins."],
      ["How is sensitive business information managed?", "The role is defined around the systems, access requirements, and working procedures your business approves. You decide which information, accounts, and responsibilities form part of the role and which matters remain restricted to your internal team."],
      ["Can the role cover both executive support and general administration?", "Yes. The role can combine executive coordination with recurring administrative work where that reflects your business needs. The responsibilities are defined during role planning so the candidate can be matched to the actual mix of work required."],
    ],
    closingHeading: "Tell us what needs coverage, which tools you use, and where industry experience matters most.",
    feedbackHeading: "What Our Executive & Administrative Virtual Support Clients Say",
    feedbackPlaceholder: "Feedback is currently being gathered.",
  },
  "/services/digital-marketing": {
    seoTitle: "Digital Marketing Virtual Assistant | Virtual Office Angels",
    metaDescription: "Find a digital marketing virtual assistant for campaign coordination, social media publishing, analytics, website updates, and content support.",
    title: "Digital Marketing Virtual Assistance",
    lead: "Virtual Office Angels matches businesses with experienced virtual assistants who support day-to-day digital marketing execution, from content publishing and strategy development to campaign coordination, reporting, and website updates.",
    tags: ["Campaign Coordination", "Social Media Publishing", "Analytics Reporting"],
    scopeEyebrow: "Digital marketing virtual assistant role scope",
    scopeHeading: "Keep marketing campaigns moving from brief to execution.",
    scopeIntro: "Build the role around the marketing work already defined by your strategy. We match the channels, systems, and production requirements to a virtual assistant with relevant digital marketing experience.",
    scope: [
      ["Content production support", "Prepare approved graphics, videos, and campaign assets from supplied briefs, templates, and brand guidelines."],
      ["Social media publishing", "Schedule and publish approved content across the social platforms selected by your business."],
      ["Campaign coordination", "Maintain campaign calendars, asset status, links, approvals, and publishing requirements across active campaigns."],
      ["Analytics reporting", "Compile traffic, engagement, and campaign data into recurring reports for your marketing team to review."],
      ["Website updates", "Upload approved pages, articles, images, and other content through your website CMS."],
      ["Search marketing support", "Assist with approved SEO, search advertising and optimisation tasks under your marketing plan."],
    ],
    systemsHeading: "Match the role to your digital marketing channels and systems.",
    systemsIntro: "Tell us which platforms, reporting tools, and content systems form part of your marketing workflow. Relevant practical experience is considered when candidates are matched to the role.",
    systems: ["Google Analytics", "Facebook & Instagram", "TikTok", "YouTube", "Meta Business Suite", "Approved Design Tools"],
    fitEyebrow: "When to hire a digital marketing virtual assistant",
    fitHeading: "Choose specialised support when marketing starts falling behind the business plan.",
    fits: [
      "Campaigns are approved, but publishing and production are not happening consistently.",
      "Content calendars, social scheduling, and website updates are building up between campaigns.",
      "Reporting needs to happen regularly so your team can see what is working and what needs attention.",
      "The role requires someone who already understands digital marketing channels, content workflows, and reporting tools.",
    ],
    boundaryLabel: "Clear role boundaries",
    boundaryHeading: "Support works best with defined authority and review.",
    boundaryText: "The virtual assistant executes approved tasks and reports results. Brand strategy, budgets, claims, campaign approvals and access permissions remain with your authorised marketing or business lead.",
    managedEyebrow: "Managed virtual support for Australian businesses",
    managedHeading: "We manage your digital marketing virtual assistant beyond recruitment.",
    managedIntro: "Virtual Office Angels manages the staffing relationship so your marketing team has consistent execution support across campaigns, content, and reporting.",
    managedSteps: [
      "Set the channels, marketing tasks, systems, working hours, and approval requirements.",
      "Assess candidates against the content, campaign, and platform experience your marketing activity requires.",
      "Introduce your virtual assistant to your brand guidelines, content workflow, systems, and approval process.",
      "Receive ongoing HR, payroll, and team support after placement.",
    ],
    faqHeading: "Digital Marketing Virtual Assistant FAQs",
    faqIntro: "Quick answers about campaign execution, marketing channels, and how a digital marketing virtual assistant works with your existing strategy.",
    faqs: [
      ["What can a digital marketing virtual assistant do?", "A digital marketing virtual assistant can support content production, social media publishing, campaign coordination, analytics reporting, website updates, and approved SEO or search marketing tasks. The exact responsibilities depend on your channels, systems, and marketing plan. Virtual Office Angels’ current service also covers graphic design, video editing, social media management, and website traffic monitoring."],
      ["Can the role focus on selected marketing channels?", "Yes. The role can be built around the channels your business actively uses, such as social media, website content, search marketing, or campaign reporting. The required platform experience is considered during candidate matching."],
      ["Who approves campaigns and published content?", "Your business sets the approval process. The virtual assistant works from approved briefs, content, budgets, and campaign instructions, while your authorised marketing team makes strategic decisions and gives final approval."],
      ["Can a virtual assistant help with SEO and digital advertising?", "Yes. Where the candidate has relevant experience, the role can include approved SEO, SEM, and digital campaign support within the strategy, budgets, and access permissions set by your business. SEO, search engine marketing, and campaign support are all part of Virtual Office Angels’ existing digital marketing service scope."],
    ],
    closingHeading: "Tell us what needs coverage, which tools you use, and where digital marketing experience matters most.",
    feedbackHeading: "What Our Digital Marketing Virtual Support Clients Say",
    feedbackPlaceholder: "Feedback is currently being gathered.",
  },
  "/services/sales-marketing": {
    seoTitle: "Sales & E-Commerce Virtual Assistant Support | VOA",
    metaDescription: "Find a sales and e-commerce virtual assistant for lead management, Shopify administration, customer enquiries, order processing, and fulfilment support.",
    title: "Sales & E-Commerce Virtual Assistance",
    lead: "Virtual Office Angels matches businesses with experienced virtual assistants who support lead management, customer enquiries, Shopify administration, order processing, and day-to-day sales activity.",
    tags: ["Lead Management", "Shopify Support", "Order Processing"],
    scopeEyebrow: "Sales & e-commerce virtual assistant role scope",
    scopeHeading: "Keep leads moving and online orders on track.",
    scopeIntro: "Build the role around the recurring work behind your sales pipeline and online store. We match the tasks, systems, and customer-service requirements to a virtual assistant with relevant sales and e-commerce experience.",
    scope: [
      ["Lead research", "Research prospective customers, build agreed lead lists and organise contact information for your sales team."],
      ["CRM administration", "Update lead records, sales stages, notes, follow-up dates and customer information in your CRM."],
      ["Customer enquiries", "Respond to agreed sales and order enquiries, provide approved information and direct complex requests to your team."],
      ["Shopify administration", "Update product information, customer details and routine store content within your approved Shopify processes."],
      ["Order validation", "Review incoming orders against your process, check required details, and flag incomplete or unusual orders for review."],
      ["Fulfilment coordination", "Track order progress, update customers and coordinate routine follow-ups with your internal team or fulfilment providers."],
    ],
    systemsHeading: "Match the role to your sales and e-commerce systems.",
    systemsIntro: "Tell us which CRM, online store, and order-management tools your business uses. Relevant platform experience forms part of the candidate matching process.",
    systems: ["Shopify", "Your CRM", "Customer Support Tools", "Order Management", "Reporting Tools"],
    fitEyebrow: "When to hire a sales & e-commerce virtual assistant",
    fitHeading: "Choose specialised support when your sales pipeline becomes harder to manage.",
    fits: [
      "New leads are coming in, but CRM updates and follow-ups are not always completed on time.",
      "Customer questions about products, orders, or delivery need regular attention.",
      "Shopify updates and routine store administration are competing with sales and business-development work.",
      "Orders need consistent checking, tracking, and follow-up from purchase through to fulfilment.",
    ],
    boundaryLabel: "Clear role boundaries",
    boundaryHeading: "Support works best with defined authority and review.",
    boundaryText: "The virtual assistant works from your approved scripts, offers, permissions and contact policies. Pricing decisions, commercial commitments, contract approval and regulated marketing responsibilities stay with authorised staff.",
    managedEyebrow: "Managed virtual support for Australian businesses",
    managedHeading: "We manage your sales and e-commerce virtual assistant beyond recruitment.",
    managedIntro: "Virtual Office Angels manages the staffing relationship so your business has consistent support across lead administration, customer enquiries and e-commerce operations.",
    managedSteps: [
      "Set the sales tasks, Shopify responsibilities, systems, working hours, and approval levels required.",
      "Assess candidates against your CRM, customer service, order-processing, and e-commerce requirements.",
      "Introduce your virtual assistant to your sales process, Shopify store, customer-service standards, and order workflow.",
      "Receive ongoing HR, payroll, and team support after placement.",
    ],
    faqHeading: "Sales & E-Commerce Virtual Assistant FAQs",
    faqIntro: "Quick answers about lead management, Shopify support, customer enquiries, and online order administration.",
    faqs: [
      ["What can a sales and e-commerce virtual assistant do?", "A sales and e-commerce virtual assistant can support lead research, CRM administration, customer enquiries, Shopify updates, order validation, and fulfilment follow-up. The exact role is built around your existing sales process, online store, and customer-service requirements."],
      ["Can a virtual assistant help manage our Shopify store?", "Yes. Where relevant Shopify experience forms part of the role, a virtual assistant can support routine store administration such as updating approved product information, maintaining customer and order details, and assisting with day-to-day e-commerce tasks. Access and responsibilities are set by your business."],
      ["Can the virtual assistant support lead generation and follow-up?", "Yes. The role can include prospect research, lead-list development, CRM updates, and approved follow-up activity based on your sales process. Lead generation and inbound and outbound customer activity are already part of our existing sales virtual support services."],
    ],
    closingHeading: "Tell us what needs coverage, which tools you use, and where sales and e-commerce experience matters most.",
    feedbackHeading: "What Our Sales & E-Commerce Virtual Support Clients Say",
    feedbackPlaceholder: "Feedback is currently being gathered.",
  },
  "/services/it-technology": {
    seoTitle: "IT Virtual Assistant & Technology Support | VOA",
    metaDescription: "Find an IT virtual assistant for WordPress support, website maintenance, troubleshooting, traffic monitoring, and recurring technical tasks.",
    title: "Virtual IT Service & Technology Support",
    lead: "Virtual Office Angels matches businesses with experienced virtual assistants who support website maintenance, WordPress administration, troubleshooting, and recurring technical tasks across your digital systems.",
    tags: ["Website Maintenance", "WordPress Support", "Technical Troubleshooting"],
    scopeEyebrow: "IT and technology virtual assistant service scope",
    scopeHeading: "Keep websites and digital systems maintained, updated, and working.",
    scopeIntro: "Build the role around the recurring technical work your business needs covered. We match your websites, platforms, and support needs with a virtual assistant who has relevant IT and web experience.",
    scope: [
      ["Website maintenance", "Update website content, pages, images, and routine site elements while keeping agreed changes organised and current."],
      ["WordPress support", "Manage approved WordPress updates, plugins, site content, and routine maintenance within your existing setup."],
      ["Website troubleshooting", "Investigate common website issues, document findings, and resolve or escalate problems based on the level of access provided."],
      ["Interface support", "Assist with website and mobile interface updates, page layouts, and approved UI changes based on supplied requirements."],
      ["Traffic monitoring", "Monitor website traffic and compile agreed performance data so your team can review site activity and changes over time."],
      ["Technical setup support", "Assist with approved product installation, configuration, and software updates within documented technical procedures."],
    ],
    systemsHeading: "Match the role to your IT and technology requirements.",
    systemsIntro: "Tell us which website platforms, plugins, analytics tools, and technical systems form part of the role. Relevant experience is considered when candidates are matched to your requirements.",
    systems: ["WordPress", "Website CMS", "Website Plugins", "Analytics Platforms", "Technical Support Tools"],
    fitEyebrow: "When to hire an IT & technology virtual assistant",
    fitHeading: "Choose specialised support when website and technical tasks need regular attention.",
    fits: [
      "Website updates and plugin maintenance are being delayed because no one has clear ownership.",
      "Small technical issues are interrupting day-to-day work or remaining unresolved longer than they should.",
      "Website traffic and performance need regular monitoring rather than occasional checks.",
      "Your business needs ongoing WordPress or website support without relying on ad hoc technical fixes.",
    ],
    boundaryLabel: "Clear role boundaries",
    boundaryHeading: "Support works best with defined authority and review.",
    boundaryText: "Access, change approval, backups, security controls and escalation paths are defined by your technical owner. High-risk infrastructure changes, security decisions and work outside the agreed technical authority remain with qualified authorised personnel.",
    managedEyebrow: "Managed virtual support for Australian businesses",
    managedHeading: "We manage your IT and technology virtual assistant beyond recruitment.",
    managedIntro: "Virtual Office Angels manages the staffing relationship so your business has consistent support for recurring website and technology tasks.",
    managedSteps: [
      "Set the websites, technical tasks, platforms, access levels, and working requirements.",
      "Assess candidates against your WordPress, website maintenance, and technical support requirements.",
      "Introduce your virtual assistant to your websites, systems, plugins, procedures, and escalation process.",
      "Receive ongoing HR, payroll, and team support after placement.",
    ],
    faqHeading: "IT Service & Technology Virtual Assistant FAQs",
    faqIntro: "Quick answers about website maintenance, WordPress support, troubleshooting, and how virtual IT support works within your existing systems.",
    faqs: [
      ["What can an IT virtual assistant support?", "An IT virtual assistant can support website maintenance, WordPress administration, plugin updates, website troubleshooting, interface updates, traffic monitoring, and approved technical setup tasks. The exact responsibilities depend on your systems, access requirements, and technical needs. Our existing IT service also includes web development, mobile interface assistance, and product installation or configuration support."],
      ["Can a virtual assistant maintain our WordPress website?", "Yes. Where relevant WordPress experience forms part of the role, a virtual assistant can support routine content changes, plugin updates, website maintenance, and approved technical adjustments. WordPress development and website maintenance are specifically included in Virtual Office Angels’ current IT services."],
      ["Can the virtual assistant troubleshoot website problems?", "Yes. The role can include investigating common website issues, carrying out approved fixes, and escalating problems that require higher-level technical expertise."],
      ["Can the role include website development work?", "Yes, where the required development experience is part of the candidate brief. Our existing service includes website creation and development, mobile interface work, UI design assistance, and WordPress development."],
    ],
    closingHeading: "Tell us what needs coverage, which tools you use, and where IT experience matters most.",
    feedbackHeading: "What Our Virtual IT Service & Technology Support Clients Say",
    feedbackPlaceholder: "Feedback is currently being gathered.",
  },
  "/services/creative-copywriting": {
    seoTitle: "Copywriting Virtual Assistant Support | Virtual Office Angels",
    metaDescription: "Find a copywriting virtual assistant for article writing, website content, proofreading, research, blog management, and ongoing publishing support.",
    title: "Copywriting Virtual Assistant Support",
    lead: "Virtual Office Angels matches businesses with experienced copywriting virtual assistants who support article writing, website content, proofreading, research, and ongoing content production.",
    tags: ["Article Writing", "Website Copy", "Content Publishing"],
    scopeEyebrow: "Copywriting virtual assistant service scope",
    scopeHeading: "Keep content moving from brief to publication.",
    scopeIntro: "Build the role around the content your business needs to produce regularly. We match the writing requirements, subject matter, and publishing workflow to a virtual assistant with relevant copywriting experience.",
    scope: [
      ["Article writing", "Draft articles from approved topics, briefs, research, and brand guidelines for your website or publication schedule."],
      ["Website content", "Write and update website copy using your approved messaging, service information, and target audience requirements."],
      ["Proofreading", "Review content for grammar, clarity, consistency, spelling and formatting before it is approved for publication."],
      ["Content research", "Research approved topics, sources and supporting information to help writers develop accurate, useful content."],
      ["Blog administration", "Format and upload approved articles, manage blog details, and keep scheduled content organised in your CMS."],
      ["Publishing support", "Prepare approved content for publication, update links and formatting, and complete agreed publishing checks."],
    ],
    systemsHeading: "Match the role to your content workflow.",
    systemsIntro: "Tell us where content is written, reviewed, and published. We factor your CMS, document tools and editorial process into the role requirements.",
    systems: ["Website CMS", "Shared Documents", "Editorial Calendars", "Research Sources", "Brand Guidelines"],
    fitEyebrow: "When to hire a copywriting virtual assistant",
    fitHeading: "Choose specialised support when content production starts to fall behind.",
    fits: [
      "Articles and website updates are planned, but there is not enough writing capacity to produce them consistently.",
      "Drafts need regular proofreading and editing before they are ready to publish.",
      "Writers need research and source material organised before content production begins.",
      "Blog uploads, formatting and publication tasks are delaying an otherwise approved content schedule.",
    ],
    boundaryLabel: "Clear role boundaries",
    boundaryHeading: "Support works best with defined authority and review.",
    boundaryText: "The virtual assistant works from approved briefs and sources. Your business retains responsibility for factual claims, legal or compliance review, brand approval and final publication decisions.",
    managedEyebrow: "Managed virtual support for Australian businesses",
    managedHeading: "We manage your copywriting virtual assistant beyond recruitment.",
    managedIntro: "Virtual Office Angels manages the staffing relationship so your business has consistent writing and publishing support for ongoing content needs.",
    managedSteps: [
      "Set the content types, writing volume, topics, publishing requirements, and working hours.",
      "Assess candidates against your writing requirements, subject matter, and content workflow.",
      "Introduce your virtual assistant to your brand voice, briefs, editorial process, and publishing systems.",
      "Receive ongoing HR, payroll, and team support after placement.",
    ],
    faqHeading: "Copywriting Virtual Assistant FAQs",
    faqIntro: "Quick answers about writing, proofreading, publishing, and how a copywriting virtual assistant can fit into your content process.",
    faqs: [
      ["What can a copywriting virtual assistant do?", "A copywriting virtual assistant can support article writing, website content, proofreading, research, blog administration and publication. The role can be built around the types of content your business produces and the editorial process already in place."],
      ["Can the virtual assistant write in our brand voice?", "Yes. Your brand guidelines, existing content, preferred terminology, and editorial requirements can form part of the onboarding process so the writer understands how your business communicates."],
      ["Can a copywriting virtual assistant research article topics?", "Yes. Research can form part of the role where required. The virtual assistant can gather information and source material around approved topics to support article and website content development."],
      ["Can the virtual assistant upload and publish content?", "Yes. Where your role includes publishing support, the virtual assistant can format and upload approved articles or website content through your CMS and complete agreed pre-publication checks."],
    ],
    closingHeading: "Tell us what needs coverage, which tools you use, and where copywriting experience matters most.",
    feedbackHeading: "What Our Virtual Copywriting Service Clients Say",
    feedbackPlaceholder: "Feedback is currently being gathered.",
  },
};
